namePrefix: terraform

resources:
  - ../empty.yaml

openapi:
  path: ../../openapis/plans-v1alpha1.json

patches:
  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/destroy.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/output.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/apply.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/plan.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/init.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/gcloud/login.yaml
