apiVersion: plans.flare.engineering/v1alpha1
kind: Plan
metadata:
  name: -plan
spec:
  upsert:
    - args:
        - apply
        - -input=false
        - -auto-approve
        - $TF_PLAN_FILE
      command: terraform
      image:
        url: hashicorp/terraform
        version: 1.0.0
      condition: Environment.REPOSITORY_BRANCH == ""
      name: terraform-apply
      workDir: ${{ .Inputs.workDir }}
