apiVersion: plans.flare.engineering/v1alpha1
kind: Plan
metadata:
  name: -plan
spec:
  delete:
    - args:
        - destroy
        - -input=false
        - -auto-approve
      command: terraform
      image:
        url: hashicorp/terraform
        version: 0.13.5
      condition: Environment.REPOSITORY_BRANCH == ""
      name: terraform-destroy
      workDir: ${{ .Inputs.workDir }}
