apiVersion: plans.flare.engineering/v1alpha1
kind: Plan
metadata:
  name: -plan
spec:
  environment:
    TF_IN_AUTOMATION: "true"
    TF_PLAN_FILE: "tfplan"
  upsert:
    - name: terraform-init
      image:
        url: hashicorp/terraform
        version: 1.0.0
      command: terraform
      workDir: ${{ .Inputs.workDir }}
      args:
        - init
        - -backend-config=bucket=${{ .Inputs.terraform.bucket }}
        - -backend-config=prefix=${{ .Inputs.terraform.prefix }}
  delete:
    - name: terraform-init
      image:
        url: hashicorp/terraform
        version: 1.0.0
      command: terraform
      workDir: ${{ .Inputs.workDir }}
      args:
        - init
        - -backend-config=bucket=${{ .Inputs.terraform.bucket }}
        - -backend-config=prefix=${{ .Inputs.terraform.prefix }}
