apiVersion: plans.flare.engineering/v1alpha1
kind: Plan
metadata:
  name: -plan
spec:
  upsert:
    - args:
        - -c
        - |
          set -eu
          terraform output -json > /workspace/checkout/outputs.json
      command: /bin/sh
      image:
        url: hashicorp/terraform
        version: 1.0.0
      condition: Environment.REPOSITORY_BRANCH == ""
      name: terraform-output
      outputs: outputs.json
      workDir: ${{ .Inputs.workDir }}
