apiVersion: plans.flare.engineering/v1alpha1
kind: Plan
metadata:
  name: -plan
spec:
  upsert:
    - args:
        - plan
        - -input=false
        - -out=$TF_PLAN_FILE
      command: terraform
      image:
        url: hashicorp/terraform
        version: 1.0.0
      name: terraform-plan
      workDir: ${{ .Inputs.workDir }}

  delete:
    - args:
        - plan
        - -input=false
        - -destroy
        - -out=$TF_PLAN_FILE
      command: terraform
      image:
        url: hashicorp/terraform
        version: 1.0.0
      name: terraform-plan
      workDir: ${{ .Inputs.workDir }}
