apiVersion: plans.flare.engineering/v1alpha1
kind: Plan
metadata:
  name: go
spec:
  upsert:
    - args:
        - build
        - .
      command: docker
      image:
        url: docker
        version: 20.10.6
      name: docker-build
