namePrefix: terraform

bases:
  - ../../bases/empty

patches:
  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/gcloud/gcloud-login.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/terraform-init.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/terraform-plan.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/terraform-apply.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/terraform-output.yaml

  - target:
      group: plans.flare.engineering
      version: v1alpha1
      kind: Plan
      name: -plan
    path: ../../patches/terraform/terraform-destroy.yaml
